### ISSUE TITLE
used the same session id for two devices

### ISSUE THREAD

**Issue by kasparrov** [rchrch/homebridge-mhacwifi1-lan#2]
`7/18/2021, 4:25:46 AM] [Aircon] Unable to get available services { success: false,
  data: null,
  error: { code: 1, message: 'Login Required' } }
(node:3801) UnhandledPromiseRejectionWarning: #<Object>
(node:3801) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 20)
(node:3801) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:3801) UnhandledPromiseRejectionWarning: #<Object>
(node:3801) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 21)
[7/18/2021, 4:25:47 AM] [Aircon] Unable to refresh state { success: false,
  data: null,
  error: { code: 1, message: 'Login Required' } }`

**Comment by Almansio** [comment]
Same issue here, probably we need to give each device a different uuid and password instead of the standard "admin, admin". But somehow I can't change this when using the web ui of the wifi module, it keeps disconnecting me....any tips?

**Comment by Almansio** [comment]
> 7/18/2021, 4:25:46 AM] [Aircon] Unable to get available services { success: false, data: null, error: { code: 1, message: 'Login Required' } } (node:3801) UnhandledPromiseRejectionWarning: #<Object> (node:3801) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 20) (node:3801) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. (node:3801) UnhandledPromiseRejectionWarning: #<Object> (node:3801) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 21) [7/18/2021, 4:25:47 AM] [Aircon] Unable to refresh state { success: false, data: null, error: { code: 1, message: 'Login Required' } }

Configure each AC as a 'child bridge' and the problem is solved.

**Comment by rchrch** [comment]
Sorry for the very late response.  I haven't had any time for this project.

Did configuring child bridges for each AC solve this problem?

**Comment by Almansio** [comment]
No worries at al! First of all, thank you for the effort and making this project! It indeed solved the problem by configuring each AC as a child bridge.Again many thanks!Op 2 okt. 2022 om 03:30 heeft rchrch ***@***.***> het volgende geschreven:﻿
Sorry for the very late response.  I haven't had any time for this project.
Did configuring child bridges for each AC solve this problem?

**Comment by rchrch** [comment]
Your welcome.  Happy things worked out.
