### ISSUE TITLE
Random crashing

### ISSUE THREAD

**Issue by pssturges** [rchrch/homebridge-mhacwifi1-lan#3]
Hi,

I get the following error at random intervals. The plugin stops functioning after the error and requires a homebridge server restart to restore function. Interval between these crashes is random as far as I can tell. Anywhere from 30mins to a couple of days.

The error in this instance is triggered when an automation in Homkit changes the set temperature.

Thanks 

[homebridge.log.txt](https://github.com/rchrch/homebridge-mhacwifi1-lan/files/6882508/homebridge.log.txt)

**Comment by rchrch** [comment]
Sorry for the very late response. I haven't had any time for this project.

This error seems very similar to issue #6.  I have improved error handling when requests fail to the unit that should improve stability.  If you are still trying to use this, please try updating to version 0.3.0.

**Comment by pssturges** [comment]
OK, thanks for the update. I have been continuing to use this of the last year or so, and the problem has only occurred on rare occasions. Hopefully this can illuminate it all together!

**Comment by rchrch** [comment]
If you are still having trouble, please let me know.  Otherwise I will close this issue.

**Comment by pssturges** [comment]
So far o good. Thanks
