### ISSUE TITLE
Enhancement - WF-RAC Wifi Module

### ISSUE THREAD

**Issue by frizby66** [rchrch/homebridge-mhacwifi1-lan#7]
Hi, is it possible to get this plugin to work with the Mitsubishi WF-RAC module?

**Comment by rchrch** [comment]
Sorry.  This plugin only works with the MH-AC-WIFI-1 module.  I'm not familiar with the WF-RAC, but after some googling it looks like HomeAssistant possibly has some development efforts for this.  However, the protocol looks completely different for the WF-RAC module.

**Comment by frizby66** [comment]
Yeah, saw that someone had reverse engineered the api’s for it. If I got a list of the calls, would it be easy to clone them?

**Comment by rchrch** [comment]
I read through the [github/Mitsubishi-WF-RAC-Integration](https://github.com/jeatheak/Mitsubishi-WF-RAC-Integration) project source.  While there are a few similarities, the protocols are quite different, and it would be very difficult to implement since I don't have that wifi module.
