### ISSUE TITLE
Fan speed

### ISSUE THREAD

**Issue by jameswestcott** [rchrch/homebridge-mhacwifi1-lan#8]
Is it possible to set the fan speed to Auto?
Is it possible to adjust the fan speed in Aircon mode?

**Comment by rchrch** [comment]
I haven't been able to set the fan speed to Auto with the local-API.

You can adjust the fan speed for aircon mode.  Read the last post in issue #6 for details on how to set the fan speed for cooling, heating, and dehumidifying.
